name: Publish to Hex 

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to Hex
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16.1'
          otp-version: '26.0'
      - uses: cucumber/action-publish-hex@v1.0.0
        with:
          hex-api-token: ${{ secrets.HEX_API_TOKEN }}
